# Generated by Django 3.0.2 on 2020-05-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_plot', models.TextField()),
                ('book_pages_number', models.IntegerField()),
                ('book_release_date', models.DateField()),
                ('book_language', models.CharField(max_length=50)),
                ('book_image', models.CharField(max_length=500)),
                ('author', models.ManyToManyField(to='restapi.Author')),
                ('genres', models.ManyToManyField(to='restapi.Genre')),
            ],
        ),
    ]
